### ISSUE TITLE
Assignment B2 Feedback

### ISSUE THREAD

**Issue by iciarfernandez** [stat545ubc-2021/timediff_package#3]
Hey Yuwei,

Excellent work! 🎉  Everything looks perfect, I can see that you put a lot of effort and detail into wrapping your function from Assignment B1 into a package! My only minor comment is that you could've listed `datateachr` as a suggestion instead of a dependency in your description file, since your function doesn't actually require that package (it's only used for the examples). However, I know that many students were having issues with using datateachr and other packages containing datasets for their examples, so no points were deducted and it's all good :) 

Thank you,
Icíar

**Comment by yuweiyang223** [comment]
Thank you Iciar!
